### ISSUE TITLE
getBoundingClientRect should be an Element API

### ISSUE THREAD

**Issue by natefaubion** [purescript-web/purescript-web-html#10]
https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect

**Comment by natefaubion** [comment]
I hit this issue because I need to measure an SVGElement.

**Comment by thomashoneyman** [comment]
I think this is reasonable to address as part of the 0.14 updates.

**Comment by thomashoneyman** [comment]
We may not be able to get this in for 0.14 due to a backlog of other work, so I'm going to remove the label. We can still do this as part of a subsequent set of breaking updates to the `web` organization updating some of these modules.

**Comment by JordanMartinez** [comment]
To fix this, do we just need to change the argument [here](https://github.com/purescript-web/purescript-web-html/blob/master/src/Web/HTML/HTMLElement.purs#L145) from `HTMLElement` to `Element`?

**Comment by natefaubion** [comment]
It probably should not be in the HTMLElement module, but rather Element.
