### ISSUE TITLE
Make scrollY and scrollX `Number` instead of `Int`

### ISSUE THREAD

**Issue by i-am-the-slime** [purescript-web/purescript-web-html#21]
https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollY says that 

> If the document is rendered on a subpixel-precise device, then the returned value is also subpixel-precise and may contain a decimal component.

**Comment by hdgarrood** [comment]
Duplicate of #16

**Comment by i-am-the-slime** [comment]
Sorry

**Comment by hdgarrood** [comment]
Not a problem! 🙂
