### ISSUE TITLE
 innerText :: HTMLElement -> Effect String missing?

### ISSUE THREAD

**Issue by swuecho** [purescript-web/purescript-web-html#22]
https://github.com/JordanMartinez/learn-halogen/issues/50

**Comment by garyb** [comment]
This was omitted as it wasn't part of the HTML5 spec, as far as I know, but it seems that everything HTML5 redirects to the living standard these days.

There's `textContent` for `Node` which is a related property that might work for this use case also.

**Comment by swuecho** [comment]
thanks. `text <- textContent $ toNode element` works.
