### ISSUE TITLE
Should `HTMLInputElement` `accept` attribute be typed as a `String`?

### ISSUE THREAD

**Issue by paluh** [purescript-web/purescript-web-html#23]
If so I can provide a this minor fix.

P.S.
@garyb thanks a lot for building this comprehensive low level library! The whole `purescript-web` project is just amazing!

**Comment by garyb** [comment]
Indeed it should! Or `MediaType` (https://github.com/purescript-contrib/purescript-media-types) would be better still perhaps.

**Comment by thomashoneyman** [comment]
@paluh I think this deserves a fix for the upcoming 0.14 release -- would you be open to adding a PR for this?

**Comment by paluh** [comment]
@thomashoneyman Yeah, I'm happy to provide a PR. Should I add _media-types_ dependency and use `MediaType`?

**Comment by thomashoneyman** [comment]
I think that's the best approach. Thanks!

**Comment by paluh** [comment]
I think that `MediaType` is too narrow. We need to extend `MediaType` with other cases so we are able to represent more general patterns like `audio/*`, `image/*` or lists of file extensions like `.jpg`, `.pdf` or any combination of these (I've [somethig similar](https://github.com/purescript-webrow/webrow/blob/master/src/WebRow/HTTP/Request/Headers.purs#L29) in the _webrow_ where I handle yet another variation on the topic - HTTP request `Accept` header ;-)). Do we want to provide such a type here or leave it for the upper layer?

**Comment by thomashoneyman** [comment]
`MediaType` is just a newtype:

https://github.com/purescript-contrib/purescript-media-types/blob/d0edd84a302273de0bfbed0031bfcbd7c43f7977/src/Data/MediaType.purs#L7-L11

so I wonder if we should just add those cases to the [`Common.purs`](https://github.com/purescript-contrib/purescript-media-types/blob/main/src/Data/MediaType/Common.purs) module? Or, if that's a violation of [RFC 6838](https://tools.ietf.org/html/rfc6838#section-4.2) then perhaps we could expand that library with a `MediaPattern` type as well?

**Comment by thomashoneyman** [comment]
If this is something that many libraries (`httpure`, `webrow`, etc.) are likely to need, then it seems useful to provide a type like the one you've implemented in _webrow_ either here or by expanding `media-types`.

**Comment by paluh** [comment]
I think that unfortunately these patterns are a bit different in the case of HTTP header than here:

* We [can associate](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept#Directives) header patterns with "weight".

* It seems that it is impossible to pass file extension in the case of a header.

* In our case of the `accept` attribute we can mix file extensions together with media types and patterns (but only three?). We are not able to use `weights`.

What seems common is the usage of media type patters like `<MIME_type>/*` where `MIME_subtype` is missing. But [it seems](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#Unique_file_type_specifiers) that in the case of `accept`  attributes patterns are restricted only to `video/*`, `audio/*` and `image/*`.

I'm not able to dive into the RFCs now to search for actual spec for these types which is probably required if we want to provide a proper type here... so maybe let's just use `String` ;-)

**Comment by thomashoneyman** [comment]
😅 Perhaps just `String` for now, yes :)
