### ISSUE TITLE
Add IntersectionObserver() API

### ISSUE THREAD

**Issue by srghma** [purescript-web/purescript-web-html#26]
https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

Is it here? I cannot find it here. Should it be here?

I don't know yet what types the wrapper should have, but maybe I could help to add it if it's not here yet

**Comment by srghma** [comment]
Should the creation of `new IntersectionObserver` be effectful?

**Comment by srghma** [comment]
https://github.com/ghcjs/ghcjs-dom/blob/d17a8078b05e7b06dc2ad5553016181c20bd2f83/ghcjs-dom-jsffi/src/GHCJS/DOM/JSFFI/Generated/IntersectionObserverEntry.hs#L6

**Comment by garyb** [comment]
This has its own spec: https://w3c.github.io/IntersectionObserver/ so it should be its own library, but no we don't have it just now.

**Comment by srghma** [comment]
@garyb created a repo https://github.com/srghma/purescript-web-intersection-observer

would like to handle it to purescript-web comminity

**Comment by JordanMartinez** [comment]
This isn't a breaking change, but something that should likely be done in the next breaking change release.

**Comment by i-am-the-slime** [comment]
How can we make this happen?

**Comment by JordanMartinez** [comment]
@srghma would need to transfer his repo to this `purescript-web`, we'd need to update the registry, and then we'd need to update the repo to match the standards used throughout the rest of the `web` libs.

**Comment by srghma** [comment]
There was an error "cannot create repositories in purescript-web", so i transferred to @JordanMartinez

**Comment by JordanMartinez** [comment]
See https://github.com/purescript-web/purescript-web-intersection-observer/pull/4

**Comment by garyb** [comment]
Closing this since there's there dedicated repo for it now 🙂
