### ISSUE TITLE
Missing Web.HTML.Window.fromEventTarget

### ISSUE THREAD

**Issue by milesfrain** [purescript-web/purescript-web-html#28]
In a Halogen-Hooks example, this function needs to be [manually defined](https://github.com/thomashoneyman/purescript-halogen-hooks/blob/5a28f6c99d0a7b7a54671be17be095afc58bdbf0/examples/Example/Hooks/UseWindowWidth.purs#L53-L55).

```purs
-- This function is missing from the purescript-web-html repository
fromEventTarget :: EventTarget -> HTML.Window
fromEventTarget = unsafeCoerce
```

Is there a reason why it cannot live in this repo?

**Comment by garyb** [comment]
It certainly can't live in this repo in that form, it's completely unsafe :smile: but yeah, the usual corresponding `fromEventTarget :: EventTarget -> Maybe Window` is missing. Every `toX` coerce should have a corresponding `fromX` conversion.
