### ISSUE TITLE
HTMLScriptElement.purs doesn't compile

### ISSUE THREAD

**Issue by arrowd** [purescript-web/purescript-web-html#31]
I'm using PureScript 0.13.8 and Spago 0.15.2.

I created a new project with `spago init`, added `"halogen"` and `"halogen-select"`, to `dependencies` field, ran `spago build` and it resulted in

```
Compiling Web.HTML.HTMLScriptElement
Error found:
at .spago/web-html/v2.3.0/src/Web/HTML/HTMLScriptElement.purs:1:1 - 75:69 (line 1, column 1 - line 75, column 69)

  Unable to parse foreign module:

    .spago/web-html/v2.3.0/src/Web/HTML/HTMLScriptElement.js


    The module could not be parsed:


    AsyncToken {tokenSpan = TokenPn 1062 57 30, tokenLiteral = "async", tokenComment = []}



See https://github.com/purescript/documentation/blob/master/errors/ErrorParsingFFIModule.md for more information,
or to contribute content related to this error.
```

**Comment by garyb** [comment]
Did you build the version of PureScript you're using yourself by any chance? This doesn't seem to happen with the released binaries, so I wonder if it's built against a different version of `language-javascript` that makes `async` a reserved word now.

**Comment by hdgarrood** [comment]
I think we should start nailing down the `language-javascript` version to an exact version in the compiler's cabal file, so that people who build the compiler themselves with cabal will still get the same version.

**Comment by arrowd** [comment]
Yep, I building the compiler manually. So, downgrading `language-javascript` should fix my problem?

**Comment by garyb** [comment]
I would think so, yep! I'm not sure what version to suggest using though... `0.7.0.0` is probably fine, as that's the lower bound we have set, but would you know which version in particular 0.13.8 was built with @hdgarrood?

**Comment by hdgarrood** [comment]
Yeah, it's 0.7.0.0, you can check by getting the compiler repo and running `git checkout v0.13.8 && stack ls dependencies | grep language-javascript`.

**Comment by arrowd** [comment]
I confirm this fixes problem for me. Thanks.

**Comment by garyb** [comment]
Glad to hear it!

**Comment by Bargsteen** [comment]
Hi, I have installed Purescript using Homebrew, and I get the same error. Any suggestions as to how I can fix it? :)

**Comment by hdgarrood** [comment]
You will need to use a different installation method; I'd recommend either building the compiler from source as described in the INSTALL.md file in purescript/purescript, or obtaining it from npm.

**Comment by garyb** [comment]
Hmm, that's unfortunate, as it sounds like the version on Homebrew was compiled with the wrong version also.

Could you install it using `npm` instead? That's the only version the core team maintains, aside from the binaries on the GH release page.

**Comment by Bargsteen** [comment]
I'll try installing it through `npm` and get back to you ;) Thanks for the quick responses!

**Comment by Bargsteen** [comment]
That fixed the problem. Thanks ;) It would be great if it worked with Homebrew though. Is the problem caused by using older versions of the repo in this file (as specified by the hashes) ? https://github.com/Homebrew/homebrew-core/blob/master/Formula/purescript.rb

**Comment by hdgarrood** [comment]
The problem is that `purescript` has a lax upper bound on `language-javascript`, the library which parses the JS, so a different version of `language-javascript` ends up being selected when you install with homebrew is different to the one used for the prebuilt binaries. This is something we'll need to address inside the compiler.

**Comment by hdgarrood** [comment]
I've just added a metadata revision on hackage to restrict this upper bound. @Bargsteen could you try again with homebrew please?

**Comment by Bargsteen** [comment]
@hdgarrood It works with Homebrew again. Awesome job, thanks! ;)

**Comment by hdgarrood** [comment]
Good to hear, thanks for checking :)
