### ISSUE TITLE
Why should pass window object for calling it's methods?

### ISSUE THREAD

**Issue by the-dr-lazy** [purescript-web/purescript-web-html#33]
I'm just curious about the pattern used in this standard library API for interacting with JavaScript `window` object methods.
Why should pass window object every time calling an effectful function like `requestAnimationFrame`?

```purs
requestAnimationFrame :: Window -> Effect Unit -> Effect RequestAnimationFrameId

-- Why not this?
requestAnimationFrame :: Effect Unit -> Effect RequestAnimationFrameId
```

**Comment by hdgarrood** [comment]
I think requiring the `window` argument is preferable because it means that you don’t need to make any assumptions about what’s available in the global scope. Not all JS environments have a `window` global, eg Node.

**Comment by the-dr-lazy** [comment]
But isn't this library based on w3c standard?
Lot's of functions in this library is **just** for working with browser API (DOM, History, Navigator, Location) and doesn't work in Node.js.

**Comment by hdgarrood** [comment]
Yes, I know; my point is that the Window argument means that this is visible in the type.

**Comment by the-dr-lazy** [comment]
That makes sense, thank you.
