### ISSUE TITLE
How to set style attribute?

### ISSUE THREAD

**Issue by singpolyma** [purescript-web/purescript-web-html#38]
Looking for the equivalent of:

```
el.style.clipPath = "circle(100px at 10px 20px)";
```

I expected this to be on `HTMLElement` but I don't see a `setStyle` or anything similar. Am I just missing it somewhere? Is it in another package?

Thanks.

**Comment by garyb** [comment]
It should be part of https://github.com/purescript-web/purescript-web-cssom as it's defined by the `ElementCSSInlineStyle` interface specified in the CSSOM spec, but it doesn't appear to be present there either - that library needs some love I think.

**Comment by singpolyma** [comment]
Thanks!  I've implemented over there: https://github.com/purescript-web/purescript-web-cssom/pull/2
