### ISSUE TITLE
Breaking change introduced

### ISSUE THREAD

**Issue by pete-murphy** [purescript-web/purescript-web-html#68]
I inadvertently added (what I think would be considered) a breaking change here: https://github.com/purescript-web/purescript-web-html/pull/55.

That added some unnamed type class instances, which are only supported in PureScript >= 0.14.2. `purescript-react-basic-dom` specifies a `purescript` version at [`^0.14.0`](https://github.com/lumihq/purescript-react-basic-dom/blob/a1d9325a6a76c95f76444ad560ea382545bfe97d/package.json#L24) and a `purescript-web-html` version at [`^3.0.0`](https://github.com/lumihq/purescript-react-basic-dom/blob/a1d9325a6a76c95f76444ad560ea382545bfe97d/bower.json#L26), which can apparently resolve to `purescript@0.14.0` and `purescript-web-html@3.2.0` which are incompatible and leads to the CI breaking for that library: https://github.com/lumihq/purescript-react-basic-dom/pull/26. I'm raising the issue here since I could imagine other libraries being similarly affected.

I can open a PR that adds names to those instances if that's acceptable.

**Comment by thomashoneyman** [comment]
Ugh, I totally forgot about this. Yes, please open a PR that adds names to the instances and we can release it!
