### ISSUE TITLE
media queries with matchMedia

### ISSUE THREAD

**Issue by flip111** [purescript-web/purescript-web-html#81]
Could matchMedia be added as a function to the `Window` type? https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia

**Comment by garyb** [comment]
If you looked at the issue template before you deleted it you'd see it asks for spec references not MDN 😛 

This feature is part of the CSSOM View Module, there's a library for that here that supports `matchMedia`: https://github.com/keijokapp/purescript-web-cssom-view - it's not part of `purescript-web` just now, but I'm going to get that rolling [as the author has asked making that so](https://github.com/keijokapp/purescript-web-cssom-view/issues/3).

**Comment by flip111** [comment]
Thanks for the response, seems very reasonable. I will close the issue since you have it on the radar
