### ISSUE TITLE
Add “opener” function in the Window Module

### ISSUE THREAD

**Issue by Woody88** [purescript-web/purescript-web-html#9]
Hey guys, I noticed that the opener function is not in the Window module.

Here is the link:
https://developer.mozilla.org/en-US/docs/Web/API/Window/opener

I can make a PR for it if you will accept it. 
Please let me know!

**Comment by jonathanlking** [comment]
Closely related, we are also missing[ `Window.parent`](https://developer.mozilla.org/en-US/docs/Web/API/Window/parent) and [`Window.frames`](https://developer.mozilla.org/en-US/docs/Web/API/Window/frames).

I imagine the suitable type for `parent` would be `parent :: Window -> Effect Window` however `frames` would be slightly more difficult/interesting :smile_cat: (as according to the docs it's not an actual array).

**Comment by garyb** [comment]
If it appears in the spec, we'll accept it 🙂 (https://www.w3.org/TR/html5)

- `opener` is there, typed as `any` which is a little unfortunate - so it'd be `Foreign` here I guess
- the suggested `parent` implementation sounds good 
- `frames` is a `WindowProxy` (which for the purposes of us is just `Window` again), it seems like we need a function to index the frames on a `Window`, along with the `length`

**Comment by jonathanlking** [comment]
From the spec:
> The opener IDL attribute on the Window object, on getting, must return the WindowProxy object of the browsing context from which the current browsing context was created (its opener browsing context), if there is one, if it is still available, and if the current browsing context has not disowned its opener; otherwise, it must return null.

In this spirit, would you be happy with `opener :: Window -> Effect (Maybe Window)`, rather than `Foreign`?

(Thanks for the feedback!)

Edit: `opener` should take a `Window` as an argument

**Comment by garyb** [comment]
That's strange, since they do usually have a nullable`?` annotation in the IDLs, maybe it's because this is settable as well as gettable. But yep, that sounds like a much better type :smile:.
